services:

  nginx:
    ports:
      - 80:80
    depends_on:
      - back
      - database
    build: 
        context: .

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=esir
      - POSTGRES_DB=assoDeRennes
      - POSTGRES_USER=esir
    volumes:
      - database_data:/var/lib/postgresql/data

  back:
    depends_on:
      - database
      - rabbitmq
    environment:
      - DB_HOST=database
      - DB_USER=esir
      - DB_PASSWORD=esir
      - DB_DATABASE=assoDeRennes
      - DB_PORT=5432
      - RABBITMQ_URL=amqp://esir:esir@mom:5672
      - DEFAULT_USER_PASS=admin
      - DEFAULT_USER_EMAIL=admin@administration.fr
    build:
      context: back/
  
  rabbitmq:
    build:
      context: rabbitmq/
    image: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=esir
      - RABBITMQ_DEFAULT_PASS=esir
      - RABBITMQ_NODE_PORT=5672

  quarkus:
    build :
      context: quarkus/
      target: prod
    depends_on:
      - rabbitmq
    restart: always
    environment:
      - EMAIL_FROM=sterenn.lehir@gmail.com
      - EMAIL_HOST=smtp
      - EMAIL_PORT=1080
      - RABBITMQ_HOST=mom
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=esir
      - RABBITMQ_PWD=esir
      - RABBITMQ_QUEUE=mail
      - QUARKUS_MAILER_HOST=smtp

  smtp:
    image: maildev/maildev:2.0.5
    restart: always

volumes:
    database_data:
