services:

  nginx:
    ports:
      - 80:80
    depends_on:
      - back
      - database
    build: 
        context: .
        target: dev
    command: sh -c "npm install && ng serve --host 0.0.0.0 --disable-host-check"
    volumes: 
      - front:/app/src:ro

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=esir
      - POSTGRES_DB=assoDeRennes
      - POSTGRES_USER=esir
    volumes:
      - database_data:/var/lib/postgresql/data

  back:
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=esir
      - DB_PASSWORD=esir
      - DB_DATABASE=assoDeRennes
      - DB_PORT=5432
    build:
      context: back/
      target: dev

volumes:
    database_data:
    front:
